### ISSUE TITLE
Build failiure with openssl 1.1

### ISSUE THREAD

**Issue by mihkelvain** [open-eid/qdigidoc#57]
https://kojipkgs.fedoraproject.org//work/tasks/3827/17393827/build.log

I suspect that the reason for this failure is that fedora rawhide uses openssl v 1.1. Unfortunately I don't have a patch to offer :)

**Comment by metsma** [comment]
Seems so

/builddir/build/BUILD/qdigidoc-3.12.4/common/SslCertificate.cpp:140:28: error: invalid use of incomplete type 'EVP_PKEY {aka struct evp_pkey_st}'
  switch( EVP_PKEY_type( key->type ) )

**Comment by mihkelvain** [comment]
BTW. Similar problem with qesteidutil-3.12.3.  I don't have build.log for that atm, but if you want I can do another koji build with rawhide and openssl v 1.1

**Comment by metsma** [comment]
Did you manage build libdigidoc/libdigidocpp and other components?

**Comment by mihkelvain** [comment]
https://kojipkgs.fedoraproject.org//work/tasks/3528/17403528/build.log

libdigidocpp does not build. Meanwhile two bugs where reported downstream:
https://bugzilla.redhat.com/show_bug.cgi?id=985344
https://bugzilla.redhat.com/show_bug.cgi?id=1415937
Second one is (I think) related to openssl v1.1. First one about minizip. Would you like another issue filed against libdigidocpp and minizip?

**Comment by mihkelvain** [comment]
Fedora 26 Mass Rebuild was completed yesterday.
https://bugzilla.redhat.com/show_bug.cgi?id=1423843 (libdigidoc)
https://bugzilla.redhat.com/show_bug.cgi?id=1423844 (libdigidocpp)
https://bugzilla.redhat.com/show_bug.cgi?id=1424219 (qdigidoc)
https://bugzilla.redhat.com/show_bug.cgi?id=1424221 (qesteidutil)

So any progress with openssl 1.1 support?

Basically I need a patch before 28.02 or they will be removed from Fedora 26

**Comment by metsma** [comment]
open-eid/qesteidutil/pull/23, open-eid/qdigidoc/pull/66, libdigidocpp/pull/100, open-eid/qt-common/pull/29
